spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-vue?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml